#  WARNING: Unless you are 200% sure that you cannot break this file by changing the following configuration, don't modify it (use in-game/console commands instead).
#  To set colors, you must use Minecraft's way (§) in this file.
#  This page can help you both ways https://minecraft.gamepedia.com/Formatting_codes
#  Using "/motdchange reload" is strictly necessary after modifying this file

metrics: true
check-updates: true
rotation: false

permanent-motd: '§bServer is running smooth...%newline%§6Be happy!'
rotating-motds:
  - '§bServer is rotating smooth...%newline%§6Rotate happily!' #  First rotating motd