# Please don't edit this file unless you're 100% sure you can't break it. Use in-game/console commands instead.
# I recommend you to read the plugin's spigot page: https://www.spigotmc.org/resources/motd-changer.63607/
#
# Enable or disable MOTD Rotation (default: false)
rotation: false
# This is the list of the MOTDs, when rotation is false only the first one will be displayed.
motds:
  - "&bThe server is working smoothly%newline%&aBe happy! ^^"

# Enable if you want to display versionText at the side of the ping status. (Enabling it also sets ping status as "Incompatible Version!") (default: default)
# Possible options: default - displays server protocol | never - displays player's protocol | yes - displays incompatible protocol
# I recommend blocking the protocol version only when the server is in maintenance!
block-protocol: default
# Set the versionText when blockProtocol is enabled TODO: PLACEHOLDERS
version-text: "&4Maintenance!"
# Set this to true if you want to hide the number of players inside (default: false)
hide-players: false

# Enable the following setting to allow the plugin to check for updates. When an update is found a message will be sent to admins/ops. (default: true)
check-updates: true
# Enable the following setting to allow the plugin to automatically update the plugin. (default: true)
auto-update: true
# Disable the following setting to disable the metrics of this plugin, it just sends statistics to BStats (plugin version, server version, java version, player count, server location and operating system) (default: true)
metrics: true

# File version - Do not modify it! It may disappear!
version: 0.1