# TODO: DOCS

# Newline: %newline%

#Modify this to have another motd
permanent-motd: "§bServer is running smooth...%newline%&6Be happy!"
metrics: true
autoupdate: true

#After changing this use /setmotd reload (If you have set any temporary motd it will be lost)
